### ISSUE TITLE
I get a "missing element label" exception when a try to serialize a xsd:choise element

### ISSUE THREAD

**Issue by dportabella** [eed3si9n/scalaxb#138]
I get a "missing element label" exception when I try to serialize a xsd:choise element.
This is a compact example illustrating the error:

example XSD with xs:choice:

<pre><code>
&lt;pre&gt;&lt;code&gt;
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;xsd:schema targetNamespace=&quot;http://example.com/&quot;
            xmlns:ex=&quot;http://example.com/&quot;
            xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
            elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;qualified&quot;&gt;

  &lt;xsd:element name=&quot;customer&quot; type=&quot;ex:Customer&quot; /&gt;

  &lt;xsd:complexType name=&quot;Customer&quot;&gt;
    &lt;xsd:sequence&gt;
      &lt;xsd:element name=&quot;name&quot; type=&quot;xsd:string&quot;/&gt;
      &lt;xsd:element name=&quot;id&quot; type=&quot;xsd:string&quot;/&gt;
      &lt;xsd:element name=&quot;address&quot; type=&quot;ex:Address&quot;/&gt;
    &lt;/xsd:sequence&gt;
  &lt;/xsd:complexType&gt;

  &lt;xsd:complexType name=&quot;Address&quot;&gt;
    &lt;xsd:choice&gt;
      &lt;xsd:element name=&quot;internalAddress&quot; type=&quot;ex:InternalAddress&quot; /&gt;
      &lt;xsd:element name=&quot;ExternalAddress&quot; type=&quot;ex:ExternalAddress&quot; /&gt;
    &lt;/xsd:choice&gt;
  &lt;/xsd:complexType&gt;

  &lt;xsd:complexType name=&quot;InternalAddress&quot;&gt;
    &lt;xsd:sequence&gt;
      &lt;xsd:element name=&quot;line1&quot; type=&quot;xsd:string&quot;/&gt;
      &lt;xsd:element name=&quot;line2&quot; type=&quot;xsd:string&quot;/&gt;
    &lt;/xsd:sequence&gt;
  &lt;/xsd:complexType&gt;

  &lt;xsd:complexType name=&quot;ExternalAddress&quot;&gt;
    &lt;xsd:sequence&gt;
      &lt;xsd:element name=&quot;id1&quot; type=&quot;xsd:integer&quot;/&gt;
      &lt;xsd:element name=&quot;id2&quot; type=&quot;xsd:integer&quot;/&gt;
    &lt;/xsd:sequence&gt;
  &lt;/xsd:complexType&gt;
&lt;/xsd:schema&gt;

---
scalaxb test.xsd --package package_test --outdir src

---
import package_test.{InternalAddress, Address, Customer}

object main {
  def main(args: Array[String]) {
    val internalAddress = InternalAddress(line1 = "line111", line2 = "line222");
    println(internalAddress);
    // this works:
    println(scalaxb.toXML[package_test.InternalAddress](internalAddress, None, Some("internalAddress1"), package_test.defaultScope));

    val address = Address(scalaxb.DataRecord(internalAddress));
    println(address);
    // this thows: Exception in thread "main" java.lang.RuntimeException: missing element label.
    println(scalaxb.toXML[package_test.Address](address, None, Some("address1"), package_test.defaultScope));

    val customer = Customer(name = "john", id = "22", address = address);
    println(customer);
    // this throws: Exception in thread "main" java.lang.RuntimeException: missing element label.
    println(scalaxb.toXML[package_test.Customer](customer, None, Some("customer1"), package_test.defaultScope));
  }
}
</code></pre>

**Comment by bmontuelle** [comment]
Great job. 

For the record it also works the same way for restriction on complexContent (also generate a `DataRecord` because defined as an extension of soap `Array` :

My wsdl looks like
```xml
        <s:complexType name="ArrayPdfArray">
                <s:complexContent>
                    <s:restriction base="soapenc:Array">
                        <s:attribute ref="soapenc:arrayType" wsdl:arrayType="tns:ArrayPdf[]"/>
                    </s:restriction>
                </s:complexContent>
            </s:complexType>
```

And consumer code
```scala
ArrayPdfArray(
            arraySequence1 = Some(ArraySequence(
              any2 = scalaxb.DataRecord(None, Some("ArrayPdf"),
                  ArrayPdf(
                  //Whatever properties ArrayPdf contains
                )
              )
            )),
            attributes = Map()
          )
```
