### ISSUE TITLE
Reserved word should be escaped

### ISSUE THREAD

**Issue by dohzya** [eed3si9n/scalaxb#163]
I use some WSDL files which contains “`type`” fields. Scalaxb convert them into

``` scala
case class … (
  …
  type: Option[String]
  …
)
```

then Scala refuses to compile.

I think they should be renamed, but at least they should be escaped

``` scala
case class … (
  …
  `type`: Option[String]
  …
)
```

Of course I can't just change the name of the field :-)

**Comment by deenar** [comment]
@eed3si9n Lenses generation does not seem to  use escaping for reserved words 

 ```def Id: monocle.Lens[Case, String] = monocle.Lens[Case, String](_.Id)((_Id: String) => (case: Case) => case.copy(Id = _Id))
```
