### ISSUE TITLE
parser throws unhelpful NumberFormatException on empty xml elements violating schema 

### ISSUE THREAD

**Issue by caoilte** [eed3si9n/scalaxb#206]
I was getting an empty element returned by our SOAP server for an optional field. According to

http://scalaxb.org/nillable

this shouldn't happen (most other SOAP clients seem to swallow the problem)

I'm fine with Scalaxb exploding, however it took me a while to diagnose why from the following stack

```
[info]   scalaxb.ParserFailure: java.lang.NumberFormatException: Zero length BigInteger
[info]   at scalaxb.package$.fromXML(scalaxb.scala:15)
[info]   at venus.paris.generated.XMLProtocol$DefaultSyndicationrequestProductionFormat$$anonfun$parser$30$$anonfun$apply$29$$anonfun$apply$30.apply(xmlprotocol.scala:818)
[info]   at venus.paris.generated.XMLProtocol$DefaultSyndicationrequestProductionFormat$$anonfun$parser$30$$anonfun$apply$29$$anonfun$apply$30.apply(xmlprotocol.scala:818)
[info]   at scala.Option.map(Option.scala:145)
[info]   at venus.paris.generated.XMLProtocol$DefaultSyndicationrequestProductionFormat$$anonfun$parser$30$$anonfun$apply$29.apply(xmlprotocol.scala:818)
[info]   at venus.paris.generated.XMLProtocol$DefaultSyndicationrequestProductionFormat$$anonfun$parser$30$$anonfun$apply$29.apply(xmlprotocol.scala:818)
[info]   at scala.Option.map(Option.scala:145)
[info]   at venus.paris.generated.XMLProtocol$DefaultSyndicationrequestProductionFormat$$anonfun$parser$30.apply(xmlprotocol.scala:818)
[info]   at venus.paris.generated.XMLProtocol$DefaultSyndicationrequestProductionFormat$$anonfun$parser$30.apply(xmlprotocol.scala:815)
[info]   at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
```

An error which indicates which field had the problem would have saved me from trawling through hundreds of fields in my data and removing them by trial and error.

**Comment by jeroenvlek** [comment]
I'm facing the same issue, but for booleans. The problem seems to be that, although the elements are defined as nillable, None is only used if the element isn't there at all. If the element is present, but empty, a parse error ensues.

How should one deal with this? Unfortunately, I have no control over the XMLs I need to parse. For now I will define them as Option[String] and deal with it further along the line.
