### ISSUE TITLE
Usage of EnhancedPatternLayout prevent usage of slf4j

### ISSUE THREAD

**Issue by ylemoigne** [eed3si9n/scalaxb#227]
Hi,

I was trying to run scalaxb from gradle.

Gradle use slf4j and log4j-over-slf4j (it's in it's internal classpath)

To avoid conflict, I did the following, but it's not enouth :

```
buildscript {
    dependencies{
        classpath("org.scalaxb:scalaxb_2.10:1.1.2") {
            exclude group: 'log4j'
        }
        }
}
```

But, the usage of EnhancedPatternLayout is blocking me :(

**Comment by pbatko** [comment]
@eed3si9n log4j 1.2 reached end of life. Is it a good enough reason to migrate to newer log4j or better to slf4j?

https://logging.apache.org/log4j/1.2/
```
On August 5, 2015 the Logging Services Project Management Committee announced that Log4j 1.x had reached end of life
```
