### ISSUE TITLE
Case class limitation reached

### ISSUE THREAD

**Issue by growak** [eed3si9n/scalaxb#246]
I try to generate scala classes from a widely used xsd: http://iptc.org/std/NewsML-G2/NewsML-G2_2.15.zip and I got this error :
Implementation restriction: case classes cannot have more than 22 parameters.
[error] case class NewsContentCharacteristics(wordcount: Option[BigInt] = None,

Why not generating scala classes with companion object with apply and unapply methods instead of case classes ?

**Comment by simbo1905** [comment]
bump

**Comment by eed3si9n** [comment]
Which version of scalaxb did you use? The recent versions should just generate a large case class for Scala 2.11.

**Comment by simbo1905** [comment]
project/plugins.sbt 

```
addSbtPlugin("org.scalaxb" % "sbt-scalaxb" % "1.4.1")

resolvers += Resolver.sonatypeRepo("public")
```

build.sbt

```
import ScalaxbKeys._

name := "docmail"

scalaxbSettings

packageName in scalaxb in Compile := "docmail"

sourceGenerators in Compile <+= scalaxb in Compile
```

sbt 0.13

thin in src/main/wsdl i have the two attached files that i had to rename from .wsdl to .txt for github to allow me to attach. 



[guid.txt](https://github.com/eed3si9n/scalaxb/files/407627/guid.txt)
[DMWS.txt](https://github.com/eed3si9n/scalaxb/files/407628/DMWS.txt)

**Comment by simbo1905** [comment]
Aha bumped to scala 2.11 with build.sbt as follows: 

```
import ScalaxbKeys._

scalaVersion := "2.11.8"

name := "docmail"

scalaxbSettings

packageName in scalaxb in Compile := "docmail"

sourceGenerators in Compile <+= scalaxb in Compile
```

no longer gives case class 22 errors now errors with: 

```
[info] Compiling 12 Scala sources to /Users/simon/projects/mailmemydoc/alpha3/target/scala-2.11/classes...
[error] /Users/simon/projects/mailmemydoc/alpha3/target/scala-2.11/src_managed/main/sbt-scalaxb/scalaxb/scalaxb.scala:3: object xml is not a member of package scala
[error] import scala.xml.{Node, NodeSeq, NamespaceBinding, Elem, UnprefixedAttribute, PrefixedAttribute}
[error]              ^
[error] /Users/simon/projects/mailmemydoc/alpha3/target/scala-2.11/src_managed/main/sbt-scalaxb/scalaxb/scalaxb.scala:53: not found: type NamespaceBinding
[error]   def toScope(pairs: (Option[String], String)*): NamespaceBinding =
```

now looking into those as dependency issues.

**Comment by eed3si9n** [comment]
http://scalaxb.org/scalaxb-with-scala211

**Comment by simbo1905** [comment]
thanks!
