### ISSUE TITLE
Scala compilation error when having xml element name ending with underscore

### ISSUE THREAD

**Issue by lalloni** [eed3si9n/scalaxb#323]
When using a third party WSDL having a schema which defines an xml element with a name ending with an underscore character like:

``` xml
<element name="bla_" type="xsd:string"/>
```

Then scalaxb generates scala code with invalid syntax like:

``` scala
val bla_: String = ...
```

Which doesn't compile because scala compiler interprets ":" after "_" like part of the identifier name. 

For this to work scalaxb needs to quote the whole val name, then it compiles correctly:

``` scala
val `bla_`: String = ...
```

**Comment by varnerac** [comment]
This was fixed in https://github.com/eed3si9n/scalaxb/pull/415
