### ISSUE TITLE
Any way to avoid or manage intermediate case class for inline anonymous ComplexType sequences

### ISSUE THREAD

**Issue by bmontuelle** [eed3si9n/scalaxb#333]
Hello,

First of all thanks for all the great job you're doing. We're using scalaxb for some time with success for a wide variety of soap (or not so soap) webservices. 

My issue here regards generated case classes with XSD files. 

All the lists attributes are provided in xsd within an anonymous ComplexType containing (a bit simplified for the sake of demonstration)

    <xs:complexType name="ProductSelection">
        <xs:sequence>
          <xs:element name="DetailedRate" minOccurs="0">
            <xs:complexType>
              <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="Rate" type="Rate" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
      </xs:complexType>

The case classes generated for the DetailedRate attribute is like this 

    case class DetailedRate(detailedratesequence1: ipo.DetailedRateSequence1*)
    case class DetailedRateSequence1(Rate: ipo.Rate)
    case class ProductSelection(DetailedRate: Option[ipo.DetailedRate] = None)

Now my issue is I have a new ComplexType added since yesterday, in the same namespace, that has an element with the same name "DetailRate", in which case scalaxb continue increasing number in the name of generated case class. The probleme that it cause to me is that the new ComplexType appears first in the xsd file and thus, take DetailedRateSequence1 case class name first, and I had to rewrite existing code around the new DetailedRateSequence2 that it generated.

I cannot control the content of xsd file in any way (as long as it is valid)  but maybe there is a solution around scalaxb to avoid this issue.

Here's what I think should be possible
* Naming such intermediate case classes with the containing class name as prefix to avoid having to number them
* Using embedded case classes to not number them (never used that in scala though)
* Match this pattern in xsd and output it to an `Option[Seq[Option[Rate]]`, maybe with a new option to scalaxb

I would be interested if any of you know some workaround to this behavior.

Best regards,
Benoit

**Comment by eed3si9n** [comment]
> First of all thanks for all the great job you're doing. We're using scalaxb for some time with success for a wide variety of soap (or not so soap) webservices.

Awesome!

There's an option called `prependFamily`. Could that be used to disambiguate the types?

**Comment by bmontuelle** [comment]
Sorry I missed it reading the documentation,  it does what I thought as possibility 1, and works fine in our test case.

Thank you.
