### ISSUE TITLE
rpc/encoded wsdls are not supported in scalaxb

### ISSUE THREAD

**Issue by romainreuillon** [eed3si9n/scalaxb#334]
My code works with the version 1.2.1, when I update to the 1.3.0 version I get this error:
rpc/encoded wsdls are not supported in scalaxb

Has the support been removed or is the checker too restrictive?

**Comment by eed3si9n** [comment]
It was dropped in 1.3.0 - https://groups.google.com/d/msg/scalaxb/DZZEqCFjT-M/vqv0IcIKdjEJ

**Comment by romainreuillon** [comment]
Sad to hear that, I am using using scalaxb to generate some access code for services developed this way.

Do you think it would be hard to checkout the old code and maintain a patched version of scalaxb supporting rpc encoded wsld? (otherwise I will be stuck with scalaxb 1.2.1)

**Comment by eed3si9n** [comment]
We have relatively low traffic of commits. It shouldn't be too hard to keep up.

**Comment by urwithsumit** [comment]
I have the same need to parse a legacy wsdl which has rpc/encoding. 
What is the workaround given that i do not have the flexibility to make any wsdl changes.
