### ISSUE TITLE
Doesn't support multiple definitions with the same name from different XSD's

### ISSUE THREAD

**Issue by DomBlack** [eed3si9n/scalaxb#336]
I have two XSD's from a third party, one so for input data to their system, the other is output data on the other end.

Both have an "Address" element, however they are completely different internally. Leading to this warning:

```
WARN  [2015-07-08 18:07:50,122] xsd.ContextProcessor: Address is defined more than once.
WARN  [2015-07-08 18:07:50,122] xsd.ContextProcessor: Address is defined more than once.
```

Then the code generator only writes one Address and uses it in both places.

Is there a way to use the xsd file name as a package separator, instead of all XSD's / WSDL's being placed in the same package as a single xmlprotocol.scala ?

**Comment by eed3si9n** [comment]
See http://scalaxb.org/multiple-configs

**Comment by DomBlack** [comment]
Thanks, somehow I missed that.
