### ISSUE TITLE
Improve options for duplicated types

### ISSUE THREAD

**Issue by briantopping** [eed3si9n/scalaxb#350]
Some schemas that I don't have control over (from US IRS) use a duplicated root type for different documents. I can't imagine why they haven't differentiated these root element names appropriately (there are only four of them). 

When these situations are encountered by https://github.com/eed3si9n/scalaxb/blob/7f832d114100a226a2553274ac29d1d48df9d243/cli/src/main/scala/scalaxb/compiler/xsd/ContextProcessor.scala#L86-86, the generation of the file terminates, resulting in files that have a documentation header and no case class body. In my deployment, only the last root type defined in this manner survives.

What would be the best manner to resolve this? I found rename functions for anonymous types via #190, but nothing currently exists for duplicate named types except generate a warning. If there's no dependency in `scalaxb.toXml` on the name of the class, it seems like an optional rename of the case class would be safe. 

Thoughts?

**Comment by eed3si9n** [comment]
> Some schemas that I don't have control over (from US IRS) use a duplicated root type for different documents.

Do the different documents have different targetNamespaces?

**Comment by briantopping** [comment]
Unfortunately they do not.

I believe the intent of the overloading was exclusionary in nature. There are over 600 xsd:include statements at the top of one of them, I didn't count the other three. There's too many of them to be sure, but I'm imagining the four different versions use different sets of includes to manage the legal element set, possibly also as a means of supporting older development hardware (the build for this one set takes 40 minutes, most of it in compile).

**Comment by eed3si9n** [comment]
You probably have to hand merge the XML so it's a union of all types.
Otherwise you need to compile each document into a separate package. Not sure if that will result in to 40 x 4 minutes or not.

**Comment by briantopping** [comment]
That won't work, there's a dozen sets of these every year.

I guess I'll create a fork and muddle through it, will let you know how it goes.

**Comment by briantopping** [comment]
Seems like the only option for this particular schema distro is to implement includes and excludes for file sets. Something like https://maven.apache.org/plugins/maven-resources-plugin/examples/include-exclude.html. I'll follow up as I get something running.

**Comment by lespea** [comment]
I had this problem and went the "different packages" route.  I just wrote a quick bash script to do it using parallel and it works really well for me.  I think it'd be too confusing having to deal with very similarly named case classes, even with a good ide.
