### ISSUE TITLE
[Compiler error] AsyncHttpClientConfig interface changed

### ISSUE THREAD

**Issue by agboom** [eed3si9n/scalaxb#359]
In DispatchHttpClientsAsync, the methods setRequestTimeoutInMs and setConnectionTimeoutInMs doesn't seem to exist (anymore):

```
    lazy val http = Http.configure(_.setRequestTimeoutInMs(requestTimeout.toMillis.toInt).
      setConnectionTimeoutInMs(connectionTimeout.toMillis.toInt))
```

If I change it to the following, it compiles:

```
    lazy val http = Http.configure(_.setRequestTimeout(requestTimeout.toMillis.toInt).
      setConnectTimeout(connectionTimeout.toMillis.toInt))
```

Maybe the interface of the used `AsyncHttpClientConfig` class changed?

**Comment by bmontuelle** [comment]
This has been fixed since pull request https://github.com/eed3si9n/scalaxb/pull/352 

@eed3si9n Do you know when the next release will be ?

Thanks

**Comment by eed3si9n** [comment]
I'll work on one maybe this weekend.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/eed3si9n/scalaxb/pull/352
