### ISSUE TITLE
Having a node complexType named Package breaks compilation of generated code

### ISSUE THREAD

**Issue by mkljakubowski** [eed3si9n/scalaxb#369]
My xsd has a complexType named `a.b.c.Package` which causes:

```
[warn] Class a.b.c.scalaxb.Package$ differs only in case from a.b.c.scalaxb.package$. Such classes will overwrite one another on case-insensitive filesystems
```

and sometime breaks with SI-8305:

```
[error] error while loading 'package', class file 'a/b/c/scalaxb/Package.class' has location not matching its contents: contains class 'package'
```

I was not able to reproduce it in tests, but renaming package helped. PR on the way.

**Comment by eed3si9n** [comment]
`package` is already part of ScalaNames https://github.com/eed3si9n/scalaxb/blob/master/cli/src/main/scala/scalaxb/compiler/ScalaNames.scala#L25. Probably the fix should be checking for the list in case insensitive way.

**Comment by mkljakubowski** [comment]
I tried your solution and unfortunetly it throws and error at runtime:
```
java.lang.NoClassDefFoundError: a/b/c/scalaxb/Package (wrong name: a/b/c/scalaxb/package)
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(Unknown Source)
at something.something.dark.side(Empire)
```
I will fix the tests though.

**Comment by mkljakubowski** [comment]
Build passes @eed3si9n

**Comment by gabro** [comment]
Hey @mkljakubowski / @eed3si9n any update on this? I'm currently evaluating scalaxb and I ran into this exact issue. I can contribute a(nother) PR if its helpful but I'd like to know what's the current stance on this.

**Comment by mkljakubowski** [comment]
Hey @gabro, imo it is ready to go. I can fix comments and rebase PR if @eed3si9n thinks it is the way to go.

**Comment by FlorianDoublet** [comment]
Hi @eed3si9n, still no solution to fix this ? I really need to handle a `package` complexeType .. :/

**Comment by eed3si9n** [comment]
Here's a PR - https://github.com/eed3si9n/scalaxb/pull/581

**Comment by tyrcho** [comment]
thanks for this quickfix @eed3si9n (I work on the same project as @FlorianDoublet )

when could we hope to get 1.8.3 published ?

**Comment by FlorianDoublet** [comment]
Thanks a lot @eed3si9n ! Just as @tyrcho ask, do you have an idea about when could we hope to get 1.8.3 published ?
