### ISSUE TITLE
Multiple fault declaration in the wsdl

### ISSUE THREAD

**Issue by skisel** [eed3si9n/scalaxb#401]
Hi,

I have an issue with wsdl stubs using scalaxb 1.4.1. I have the following wsdl operation declaration:
`       

```
             <wsdl:operation name="operation">

        <wsdl:input message="tns:operationRequest"/>  

        <wsdl:output message="tns:operationResponse"/>

        <wsdl:fault message="tns:TechnicalException" name="TechnicalException"/>

        <wsdl:fault message="tns:ValidationException" name="ValidationException"/>

        <wsdl:fault message="tns:BusinessException" name="BusinessException"/>

    </wsdl:operation>
```

`

In the generated trait to handle soap side there is only one fault expected:

`
              case x: scalaxb.Soap11Fault[_] =>  x.asFault[generated.ValidationException]
`

Is there an easy workaround to fix this issue or may be can be solved already?

**Comment by skisel** [comment]
Could this be merged?

**Comment by eed3si9n** [comment]
Merged!

**Comment by skisel** [comment]
Thanks! :) is it going to be released soon?
