### ISSUE TITLE
Scala 2.12

### ISSUE THREAD

**Issue by francisdb** [eed3si9n/scalaxb#408]
I guess this is blocked by https://github.com/dispatch/dispatch/issues/104

Would it be hard to have a pluggable http client lib? Dispatch is as good as dead.

**Comment by francisdb** [comment]
I guess switching to http://eed3si9n.com/gigahorse/ would be the best way to get rid of dispatch

**Comment by eed3si9n** [comment]
Could you or @gabro explain why you guys are interested in Scala 2.12 artifact for scalaxb?
Are you driving scalaxb programmatically?

**Comment by francisdb** [comment]
http://scalaxb.org/sbt-scalaxb explains that you have to add databinder to your project and since that is not available for 2.12 I concluded that scala 2.12 is not supported?

**Comment by gabro** [comment]
@eed3si9n I admit there may be some confusion on my side about the dependencies. Since according to the readme`dispatch` is a dependency when using the sbt plugin, I was under the impression that Scala 2.12 artifacts were necessary when enabling the plugin for a Scala 2.12 project. I'd be happy to be wrong about this :)

**Comment by eed3si9n** [comment]
1. Dispatch 0.12.0 is available for Scala 2.12 - http://repo1.maven.org/maven2/net/databinder/dispatch/dispatch-core_2.12/0.12.0/
2. The code generation if done by sbt-scalaxb requires scalaxb in Scala 2.10.

**Comment by gabro** [comment]
@eed3si9n thanks, much clearer now. :)

**Comment by pbatko** [comment]
@eed3si9n we're using scalaxb programmatically, so it'd awesome to have it release for Scala 2.12. Would that be possible? :)

**Comment by eed3si9n** [comment]
I'll work on this soon.

**Comment by pbatko** [comment]
@eed3si9n Thanks, looking forward to it.

**Comment by pbatko** [comment]
@eed3si9n Should the 2.12 artifacts be already available in maven?
