### ISSUE TITLE
How to provide bindings to convert javax.xml.datatype.XMLGregorianCalendar to java.time.LocalDate

### ISSUE THREAD

**Issue by gcqst** [eed3si9n/scalaxb#430]
Hi,

Maybe here is not the right place to ask questions, but I do have two questions regarding scalaxb.

**Q1: Is that scalaxb can use the binding xml (like xjc) to generate LocalDate rather than XMLGregorianCalendar for date type?**

E.g.

```
<jaxb:globalBindings>
        <xjc:javaType
                adapter="ms.cm.lang.type.adaptor.LocalDateAdapter"
                name="java.time.LocalDate"
                xmlType="xs:date"/>
</jaxb:globalBindings>
```

```java
public class LocalDateAdapter extends XmlAdapter<String, LocalDate> {
    @Override
    public LocalDate unmarshal(String xmlGregorianCalendar) throws Exception {
        return LocalDate.parse(xmlGregorianCalendar, DateTimeFormatter.ISO_DATE);
    }

    @Override
    public String marshal(LocalDate value) throws Exception {
        return value.format(DateTimeFormatter.ISO_DATE);
    }
}
```

Q2: Can the param of generated class be Seq(type) rather than type* for a complex type if it only has one attribute.

```
<sequence>
            <element name="elementName" type="elementType" maxOccurs="unbounded"/>
</sequence>
```

**Comment by eed3si9n** [comment]
The issue reporting guide is here - http://scalaxb.org/issue-reporting-guideline. It's fine to use GitHub issues, but please keep it to one question per issue.

I think it would be a good idea to allow users to override the generated types, but there's no feature right now. For date case specifically there's an existing issue https://github.com/eed3si9n/scalaxb/issues/376 so I'll close this as duplicate. Please comment your interest there or subscribe the issue.

I'll open another issue for the second question.

**Comment by gcqst** [comment]
@eed3si9n Thanks for your reply. It do good to allow users to override the generated types, looking forward to that feature.
