### ISSUE TITLE
Release for sbt 1.0

### ISSUE THREAD

**Issue by gabro** [eed3si9n/scalaxb#437]
Hi @eed3si9n, this is one of the few plugins that is blocking our migration to sbt 1.0.

In case that helps, I'm listing here the plugins this depends on and whether they're compatible with sbt 1.0

- [x] sbt-assemby
- [x] sbt-buildinfo
- [ ] ~sbt-doge~ (now part of sbt 1.0)
- [x] sbt-pgp
- [ ] sbt-scalashim
- [x] scripted-plugin (part of sbt)

The only missing one is [sbt-scalashim](https://github.com/sbt/sbt-scalashim) which doesn't seem to have dependencies on its own.

Is there any plan for a release and/or can I help?

**Comment by eed3si9n** [comment]
I haven't used sbt-scalashim in a while, so I am guessing we can drop it.

**Comment by eed3si9n** [comment]
I can potentially look at the migration this weekend, but if you want to give it a shot, I'd be happy to review a PR :)

**Comment by gabro** [comment]
Sure, I just need to know whether you intend to maintain 0.13 compatibility or drop it

--
gabriele
~ buildo

**Comment by eed3si9n** [comment]
I'd definitely try to cross build across 0.13 and 1.x since 0.13 might stick around longer among the kind of people who want XML.

**Comment by gabro** [comment]
> the kind of people who want XML

I'm a kind of person *stuck* with an external XML service, so I'd be glad to work on this :D

I'll give it a shot. ;)

**Comment by gabro** [comment]
@eed3si9n I tried upgrading to 0.13.6 for cross building and then running

```
++2.12.2 ^^1.0.0 test
```
(in the `sbtPlugin` project)

and I get this compile error

```
[error] /Users/gabro/buildo/scalaxb/sbt-scalaxb/src/main/scala/sbtscalaxb/ScalaxbCompile.scala:30: could not find implicit value for parameter e: sjsonnew.JsonFormat[String]
[error]     implicitly[sjsonnew.JsonFormat[String]]
[error]               ^
[error] /Users/gabro/buildo/scalaxb/sbt-scalaxb/src/main/scala/sbtscalaxb/ScalaxbCompile.scala:33: could not find implicit value for evidence parameter of type sjsonnew.JsonFormat[Seq[sbt.File] :+: (sbt.FilesInfo[sbt.ModifiedFileInfo] :+: (String :+: sbt.HNil))]
[error]       inputChanged(cacheDir / "scalaxb-inputs") { (inChanged, inputs: Seq[File] :+: FilesInfo[ModifiedFileInfo] :+: String :+: HNil) =>
[error]     
```

I tried investigating a little, but it spirals down to some more libraries I know nothing about (sbinary, sbt-util, ...). Any pointer would be appreciated :)

**Comment by eed3si9n** [comment]
Yea. That's task caching. `inputChanged` now expects `sjsonnew.JsonFormat` typeclass (see https://github.com/eed3si9n/sjson-new), which is kind of like `scalaxb.XMLFormat` (except sjson-new is backend independent). I'd probably migrate to tuple instead of HList using [sbt version specific source directory](http://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#sbt+version+specific+source+directory).

**Comment by eed3si9n** [comment]
I ported it https://github.com/eed3si9n/scalaxb/pull/439/commits/694a80a0ce43b1f8591052d5d18b1a5afdcbe9ef. 1.5.2 is back published.

**Comment by gabro** [comment]
@eed3si9n wonderful, thanks! I wished I managed to help more :)

**Comment by eed3si9n** [comment]
oh no you totally helped by trailblazing.
