### ISSUE TITLE
How does the SBT plugin depend on 2.10?

### ISSUE THREAD

**Issue by bbarker** [eed3si9n/scalaxb#447]
I have a branch where I'm not worrying about Scala 2.10 in order to publish locally while testing things out. I disabled 2.10 everywhere I could find, however, somehow the sbt plugin still depends on it, so I disabled it:

https://github.com/bbarker/scalaxb/blob/sbt_for_bbarker.github.io/build.sbt#L17

I'm just curious how this can be? I suspect it has something to do with the ScriptedPlugin, simply because I don't see anything else that stands out.

**Comment by eed3si9n** [comment]
All sbt 0.13 plugins are built using Scala 2.10.
As scalaxb primarily runs as a code generator within a build, the "generator" should be built using 2.10, even if the source that it generates targets 2.12.
