### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by murrayc-egym** [eed3si9n/scalaxb#474]
There are several commits in master that are not yet in a release. In particular, the current release, 1.5.2, is incompatible with recent versions of dispatch:
https://github.com/eed3si9n/scalaxb/commit/c8bb3077c8edd541c3431a877594842bf01f74e6

It would be really helpful if you made a release, please.

**Comment by peterneyens** [comment]
I just published master locally as 1.6.0-SNAPSHOT and the scalaxb.g8 project built without a problem.

**Comment by jtjeferreira** [comment]
I was also able to publish master locally and use it in my project without a problem... However would be good that #477 is accepted so that the the next version is published for both sbt 0.13x and 1.x...

**Comment by jtjeferreira** [comment]
Hi @eed3si9n! Any news on this? Anything I can do to help?

**Comment by eed3si9n** [comment]
1.7.0 is out.
