### ISSUE TITLE
Spurious unused implicit ExecutionContext included in same scope as instances.

### ISSUE THREAD

**Issue by LeifW** [eed3si9n/scalaxb#478]
The generated code that you have to import to use to / from XML also includes an implicit `ExecutionContext`, e.g. https://github.com/CodersBistro/Scalaxb-Examples/blob/master/scalaxb-serde/src/main/scala/com/codersbistro/soapexample/generated/xmlprotocol.scala#L15

We already have an implicit `ExecutionContext` in scope that was passed in from elsewhere - so importing the generated xmlprotocol causes a conflict.

**Comment by eed3si9n** [comment]
Changing all use site to take an implicit parameter `ExecutionContext` would be a lot change. I think https://github.com/eed3si9n/scalaxb/pull/407 partly address this problem, but I think we need to change the name to something more unique to avoid conflict.

**Comment by LeifW** [comment]
Would having the generate `XMLFormat`s / `CanWriteXML` implicits be in a separately importable scope from that implicit `ExecutionContext` be a simple(r) work-around?

**Comment by eed3si9n** [comment]
I tried moving ExecutionContext to a implicit param, and it actually wasn't that bad - https://github.com/eed3si9n/scalaxb/pull/482/commits/691eaa4ad9a6e31eab0d0fc827ed27bc939102d3

**Comment by LeifW** [comment]
Awesome, thanks so much!
