### ISSUE TITLE
when compiling for 2.13  object breakOut is not a member of package scala.collection.breakOut

### ISSUE THREAD

**Issue by kalevsuik** [eed3si9n/scalaxb#533]
object breakOut is not a member of package collection
[error]     import scala.collection.breakOut

in generated scalaxb/scalaxb.scala
object HexBinary {
  def apply(xs: Byte*): HexBinary = {
    import scala.collection.breakOut
    val vector: Vector[Byte] = (xs.toIndexedSeq map {x: Byte => x})(breakOut)
    new HexBinary(vector)
  }
.........
I was compiling OpenAdr xsd files

**Comment by eed3si9n** [comment]
This looks like a duplicate of https://github.com/eed3si9n/scalaxb/issues/509. Are you using the latest version of scalaxb? If not could you try it?

**Comment by kalevsuik** [comment]
I'm have 1.7.5

**Comment by eed3si9n** [comment]
https://github.com/eed3si9n/scalaxb/blob/v1.7.5/cli/src/main/resources/scalaxb.scala.template#L832-L844

The HexBinary.apply doesn't match the code you quoted.

**Comment by kalevsuik** [comment]
my bad, I had latest version in build.sbt but old one in plugins.sbt
