### ISSUE TITLE
Compile in Scala 2.13

### ISSUE THREAD

**Issue by sfali** [eed3si9n/scalaxb#547]
Hi There,

I am using Scala 2.13 and getting following error:

```
package object inheritance is deprecated (https://github.com/scala/scala-dev/issues/441);
[error] drop the `extends` clause or use a regular object instead
[error] object `package` extends XMLProtocol { }
```

Any idea how what' going on?

Regards,

Syed

**Comment by eed3si9n** [comment]
@sfali I'm not aware of that. Could you tell me which version of Scala 2.13 you're using?
It seems like the deprecation of package object inheritance was reverted in https://github.com/scala/scala/pull/7857.

**Comment by sfali** [comment]
I am using Scala 2.13.4

**Comment by xuwei-k** [comment]
- https://github.com/eed3si9n/scalaxb/issues/606

**Comment by eed3si9n** [comment]
Closing this one as a duplicate.
