### ISSUE TITLE
Parsing xsd:decimal does not honor xs:whitespace = collapse

### ISSUE THREAD

**Issue by jypma** [eed3si9n/scalaxb#554]
According to the plain [xsd spec](https://www.w3.org/2001/05/datatypes.xsd), leading and trailing whitespace around a decimal value should just be ignored, e.g. in `<mytag>     15.0      </mytag>`, since `xsd:decimal` is defined with `<xs:whiteSpace value="collapse">`.

However, scalaxb's [parsing of BigDecimal](https://github.com/eed3si9n/scalaxb/blob/master/cli/src_managed/scalaxb/scalaxb.scala#L148) (and other numeric types) doesn't trim the string before parsing, resulting in a `NumberFormatException`.

It seems that URIs are trimmed though (see https://github.com/eed3si9n/scalaxb/pull/185). Should numeric types be trimmed as well? I'd be glad to create a PR for it, if agreed.

**Comment by eed3si9n** [comment]
Sounds good to me.
