### ISSUE TITLE
Release 1.8.2

### ISSUE THREAD

**Issue by eed3si9n** [eed3si9n/scalaxb#567]

**Comment by DanMaly** [comment]
Any chance this could actually be released?

**Comment by andrewinci** [comment]
Hey @eed3si9n, do you know when this will be actually released? 
Thank you

**Comment by eed3si9n** [comment]
Hopefully some time this week?

**Comment by eed3si9n** [comment]
https://github.com/eed3si9n/scalaxb/releases/tag/v1.8.2
