### ISSUE TITLE
Warning: abstract type A in type pattern ElemNameParser.this.Success[A] is unchecked, when compiling with scala 2.13.7

### ISSUE THREAD

**Issue by aleksandr-vin** [eed3si9n/scalaxb#572]
```
target/scala-2.13/src_managed/main/sbt-scalaxb/scalaxb/scalaxb.scala:795:17
abstract type A in type pattern ElemNameParser.this.Success[A] is unchecked since it is eliminated by erasure
        case x: Success[A] => Right(x.get)
```

**Comment by eed3si9n** [comment]
@aleksandr-vin Thanks for the report.

If anyone is interested in contributing, the relevant part of the code is https://github.com/eed3si9n/scalaxb/blob/cb801ed4cf24fb02e2e1e34346da1fee1a196543/cli/src/main/resources/scalaxb.scala.template#L795

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/eed3si9n/scalaxb/pull/582
