### ISSUE TITLE
Which Scala versions are supported

### ISSUE THREAD

**Issue by xuwei-k** [eed3si9n/scalaxb#629]
There are scala `2.10` and `2.11` in the `app` module `crossScalaVersions`.

https://github.com/eed3si9n/scalaxb/blob/85271ccb1c6e5f7d779152a13994d7e2e520da3e/build.sbt#L57

But maybe does not check in github actions CI.

https://github.com/eed3si9n/scalaxb/blob/85271ccb1c6e5f7d779152a13994d7e2e520da3e/build.sbt#L77
https://github.com/eed3si9n/scalaxb/blob/85271ccb1c6e5f7d779152a13994d7e2e520da3e/.github/workflows/ci.yml#L35-L37

- Should we fix ci settings?(restore scala 2.10 and 2.11 test)
- remove old scala and sbt 0.13 version settings in build files

WDYT? 👀 🤔

**Comment by eed3si9n** [comment]
Assuming most users care about sbt 1.x plugin support, I guess we can drop Scala 2.10 and 2.11, and maybe test if the generated code works in various Scala versions in the scripted test or something.
