### ISSUE TITLE
Compile error on Scala 3.5.0

### ISSUE THREAD

**Issue by jqno** [eed3si9n/scalaxb#660]
I'm upgrading our project from Scala 3.4.3 to Scala 3.5.0, and I get this new error message:

```
[error] -- Error: /home/jqno/path/to/my/project/xsd/converters/target/scala-3.5.0/src_managed/main/sbt-scalaxb/scalaxb/scalaxb.scala:727:32
 
[error] 727 |    opt(text ^^ (x => DataRecord(x.node.text)(format)))
[error]     |                      ^^^^^^^^^^^^^^^^^^^^^^^
[error]     |Context bounds will map to context parameters.
[error]     |A `using` clause is needed to pass explicit arguments to them.
[error]     |This code can be rewritten automatically under -rewrite -source 3.4-migration.
[error] one error found
```

I tried doing what the compiler suggested and added `-rewrite -source 3.4-migration` to the `scalacOptions` in our build.sbt. That changed this line:

```scala
    opt(text ^^ (x => DataRecord(x.node.text)(format)))
```

into this one:

```scala
    opt(text ^^ (x => DataRecord(x.node.text)(using format)))
```

Along with some other Scala 3-specific rewrites. I was considering offering a PR with the rewrites to fix this issue, but since these changes break compatibility with Scala 2, I see that that's not an option.

Apart from leaving the `-rewrite` flag in our build.sbt, is there a workaround or fix for this that we can apply, so that we can upgrade to Scala 3.5?

**Comment by eed3si9n** [comment]
Thanks for the report! I guess we can try not passing in implicit parameters explicitly, or have some flag that emits `using`?

**Comment by jqno** [comment]
Both options sound good. I don't know which one is more appropriate for scalaxb though?

**Comment by eed3si9n** [comment]
Try not passing it first, and if not a flag?

**Comment by eed3si9n** [comment]
<s>By the way, do you have a schema publicly that I can reproduce this error?</s>

The bug was in scalaxb.scala runtime.

**Comment by eed3si9n** [comment]
Oops. This has been fixed in https://github.com/eed3si9n/scalaxb/pull/654. I just have to release it.

**Comment by eed3si9n** [comment]
Here's a PR to get Scala 3.5.0 compiling with `-Xfatal-warnings` - https://github.com/eed3si9n/scalaxb/pull/661

**Comment by eed3si9n** [comment]
https://github.com/eed3si9n/scalaxb/releases/tag/v1.12.1

**Comment by jqno** [comment]
Awesome, thank you!
