### ISSUE TITLE
Namespace similarly named complex types used throughout multiple WSDL operations

### ISSUE THREAD

**Issue by devinus** [eed3si9n/scalaxb#69]
Right now, if two operations in package namespace `pkg` have complex types with the same name, e.g. operation `Foo` has complex type `Apple` and `Orange` and operation `Bar` has complex type `Apple` and `Orange`, the types will both be within the package namespace `pkg` as `pkg.Apple`, `pkg.Orange`, `pkg.Apple2`, `pkg.Orange2`.

Each operation should be namespaced, such that Apple and Orange in Foo and Bar become e.g. `pkg.Foo.Apple`, `pkg.Foo.Orange`, `pkg.Bar.Apple`, `pkg.Bar.Orange`.

This becomes increasingly important the more operations with types using the same names you have, as `pkg.Apple1` can quickly becomes `pkg.Apple1` to `pkg.Apple142`.

**Comment by raghu-tiwari-gemini** [comment]
Hello,

Can we include the --prepend-family in the default option here: https://github.com/eed3si9n/scalaxb/blob/develop/cli/src/main/scala/scalaxb/compiler/Config.scala?

`  val default = Config(
    Vector(defaultPackageNames, defaultOpOutputWrapperPostfix, defaultOutdir,
      defaultWrappedComplexTypes, SeperateProtocol, defaultProtocolFileName,
      defaultProtocolPackageName, GenerateRuntime, GenerateDispatchClient,
      defaultContentsSizeLimit, defaultSequenceChunkSize,
      HttpClientStyle.Future, defaultDispatchVersion)
  )
}`


As dealing with the random sequencing is a mess and this really solves the issue!

**Comment by raghu-tiwari-gemini** [comment]
Because we have a "remove" method in case it is not required.

**Comment by raghu-tiwari-gemini** [comment]
This really increases the usability

**Comment by eed3si9n** [comment]
Could we start a new issue plz instead of reopening an issue from 12 years ago?
